package com.support.appcompat;

import android.R;

/* JADX INFO: loaded from: classes2.dex */
public final class R$styleable {
    public static int COUIButtonLayout_couiLimitMaxWidth = 0;
    public static int COUIButtonLayout_horizontalLayoutPadding = 1;
    public static int COUIButtonLayout_verticalLayoutPadding = 2;
    public static int COUIButton_android_textColor = 0;
    public static int COUIButton_animEnable = 1;
    public static int COUIButton_animType = 2;
    public static int COUIButton_brightness = 3;
    public static int COUIButton_circleButton = 4;
    public static int COUIButton_closeLimitTextSize = 5;
    public static int COUIButton_couiRoundType = 6;
    public static int COUIButton_descText = 7;
    public static int COUIButton_disabledColor = 8;
    public static int COUIButton_drawableColor = 9;
    public static int COUIButton_drawableRadius = 10;
    public static int COUIButton_expandOffset = 11;
    public static int COUIButton_isDescType = 12;
    public static int COUIButton_isShowLoadingText = 13;
    public static int COUIButton_loadingText = 14;
    public static int COUIButton_needVibrate = 15;
    public static int COUIButton_pressAlpha = 16;
    public static int COUIButton_pressColor = 17;
    public static int COUIButton_scaleEnable = 18;
    public static int COUIButton_strokeColor = 19;
    public static int COUIButton_strokeWidth = 20;
    public static int COUICheckBox_couiAsyncLoad = 0;
    public static int COUICheckBox_couiButton = 1;
    public static int COUICheckBox_couiCheckBoxState = 2;
    public static int COUIEditText_android_hint = 1;
    public static int COUIEditText_android_textColorHint = 0;
    public static int COUIEditText_collapsedTextColor = 2;
    public static int COUIEditText_collapsedTextSize = 3;
    public static int COUIEditText_cornerRadius = 4;
    public static int COUIEditText_couiBackgroundMode = 5;
    public static int COUIEditText_couiDefaultStrokeColor = 6;
    public static int COUIEditText_couiDisabledStrokeColor = 7;
    public static int COUIEditText_couiEditTextDeleteIconNormal = 8;
    public static int COUIEditText_couiEditTextDeleteIconPressed = 9;
    public static int COUIEditText_couiEditTextErrorColor = 10;
    public static int COUIEditText_couiEditTextHintLines = 11;
    public static int COUIEditText_couiEditTextIsEllipsis = 12;
    public static int COUIEditText_couiEditTextNoEllipsisText = 13;
    public static int COUIEditText_couiFocusStrokeWidth = 14;
    public static int COUIEditText_couiHintAnimationEnabled = 15;
    public static int COUIEditText_couiHintEnabled = 16;
    public static int COUIEditText_couiStrokeColor = 17;
    public static int COUIEditText_couiStrokeWidth = 18;
    public static int COUIEditText_quickDelete = 19;
    public static int COUIEditText_rectModePaddingTop = 20;
    public static int COUILinearLayout_couiMaxHeight = 0;
    public static int COUILinearLayout_couiMaxWidth = 1;
    public static int COUIRoundImageView_couiBorderRadius = 0;
    public static int COUIRoundImageView_couiHasBorder = 1;
    public static int COUIRoundImageView_couiHasDefaultPic = 2;
    public static int COUIRoundImageView_couiRoundImageViewOutCircleColor = 3;
    public static int COUIRoundImageView_couiType = 4;
    public static int COUIRoundImageView_isImageView = 5;
    public static int COUIRoundImageView_sizeType = 6;
    public static int COUISwitch_barCheckedDisabledColor = 0;
    public static int COUISwitch_barHeight = 1;
    public static int COUISwitch_barUncheckedDisabledColor = 2;
    public static int COUISwitch_circlePadding = 3;
    public static int COUISwitch_innerCircleCheckedDisabledColor = 4;
    public static int COUISwitch_innerCircleColor = 5;
    public static int COUISwitch_innerCircleUncheckedDisabledColor = 6;
    public static int COUISwitch_innerCircleWidth = 7;
    public static int COUISwitch_loadingDrawable = 8;
    public static int COUISwitch_outerCircleCheckedDisabledColor = 9;
    public static int COUISwitch_outerCircleColor = 10;
    public static int COUISwitch_outerCircleStrokeWidth = 11;
    public static int COUISwitch_outerCircleUncheckedDisabledColor = 12;
    public static int COUISwitch_outerCircleWidth = 13;
    public static int COUISwitch_outerUnCheckedCircleColor = 14;
    public static int COUISwitch_themedCheckedDrawable = 15;
    public static int COUISwitch_themedLoadingCheckedBackground = 16;
    public static int COUISwitch_themedLoadingDrawable = 17;
    public static int COUISwitch_themedLoadingUncheckedBackground = 18;
    public static int COUISwitch_themedUncheckedDrawable = 19;
    public static int COUITextAppearance_android_lineSpacingMultiplier = 0;
    public static int COUITextAppearance_lineSpacingMultiplier = 1;
    public static int COUITextView_android_lineSpacingMultiplier = 1;
    public static int COUITextView_android_textAppearance = 0;
    public static int COUITheme_couiEmptyHint = 0;
    public static int COUITheme_couiIsSplitHideWithActionBar = 1;
    public static int COUITheme_isCOUIDarkTheme = 2;
    public static int COUITheme_isCOUITheme = 3;
    public static int COUITheme_startingWindowTitle = 4;
    public static int COUITheme_windowPreviewType = 5;
    public static int COUITheme_windowSnapshotPreviewToken = 6;
    public static int[] COUIButton = {R.attr.textColor, com.coloros.translate.R.attr.animEnable, com.coloros.translate.R.attr.animType, com.coloros.translate.R.attr.brightness, com.coloros.translate.R.attr.circleButton, com.coloros.translate.R.attr.closeLimitTextSize, com.coloros.translate.R.attr.couiRoundType, com.coloros.translate.R.attr.descText, com.coloros.translate.R.attr.disabledColor, com.coloros.translate.R.attr.drawableColor, com.coloros.translate.R.attr.drawableRadius, com.coloros.translate.R.attr.expandOffset, com.coloros.translate.R.attr.isDescType, com.coloros.translate.R.attr.isShowLoadingText, com.coloros.translate.R.attr.loadingText, com.coloros.translate.R.attr.needVibrate, com.coloros.translate.R.attr.pressAlpha, com.coloros.translate.R.attr.pressColor, com.coloros.translate.R.attr.scaleEnable, com.coloros.translate.R.attr.strokeColor, com.coloros.translate.R.attr.strokeWidth};
    public static int[] COUIButtonLayout = {com.coloros.translate.R.attr.couiLimitMaxWidth, com.coloros.translate.R.attr.horizontalLayoutPadding, com.coloros.translate.R.attr.verticalLayoutPadding};
    public static int[] COUICheckBox = {com.coloros.translate.R.attr.couiAsyncLoad, com.coloros.translate.R.attr.couiButton, com.coloros.translate.R.attr.couiCheckBoxState};
    public static int[] COUIEditText = {R.attr.textColorHint, R.attr.hint, com.coloros.translate.R.attr.collapsedTextColor, com.coloros.translate.R.attr.collapsedTextSize, com.coloros.translate.R.attr.cornerRadius, com.coloros.translate.R.attr.couiBackgroundMode, com.coloros.translate.R.attr.couiDefaultStrokeColor, com.coloros.translate.R.attr.couiDisabledStrokeColor, com.coloros.translate.R.attr.couiEditTextDeleteIconNormal, com.coloros.translate.R.attr.couiEditTextDeleteIconPressed, com.coloros.translate.R.attr.couiEditTextErrorColor, com.coloros.translate.R.attr.couiEditTextHintLines, com.coloros.translate.R.attr.couiEditTextIsEllipsis, com.coloros.translate.R.attr.couiEditTextNoEllipsisText, com.coloros.translate.R.attr.couiFocusStrokeWidth, com.coloros.translate.R.attr.couiHintAnimationEnabled, com.coloros.translate.R.attr.couiHintEnabled, com.coloros.translate.R.attr.couiStrokeColor, com.coloros.translate.R.attr.couiStrokeWidth, com.coloros.translate.R.attr.quickDelete, com.coloros.translate.R.attr.rectModePaddingTop};
    public static int[] COUILinearLayout = {com.coloros.translate.R.attr.couiMaxHeight, com.coloros.translate.R.attr.couiMaxWidth};
    public static int[] COUIRoundImageView = {com.coloros.translate.R.attr.couiBorderRadius, com.coloros.translate.R.attr.couiHasBorder, com.coloros.translate.R.attr.couiHasDefaultPic, com.coloros.translate.R.attr.couiRoundImageViewOutCircleColor, com.coloros.translate.R.attr.couiType, com.coloros.translate.R.attr.isImageView, com.coloros.translate.R.attr.sizeType};
    public static int[] COUISwitch = {com.coloros.translate.R.attr.barCheckedDisabledColor, com.coloros.translate.R.attr.barHeight, com.coloros.translate.R.attr.barUncheckedDisabledColor, com.coloros.translate.R.attr.circlePadding, com.coloros.translate.R.attr.innerCircleCheckedDisabledColor, com.coloros.translate.R.attr.innerCircleColor, com.coloros.translate.R.attr.innerCircleUncheckedDisabledColor, com.coloros.translate.R.attr.innerCircleWidth, com.coloros.translate.R.attr.loadingDrawable, com.coloros.translate.R.attr.outerCircleCheckedDisabledColor, com.coloros.translate.R.attr.outerCircleColor, com.coloros.translate.R.attr.outerCircleStrokeWidth, com.coloros.translate.R.attr.outerCircleUncheckedDisabledColor, com.coloros.translate.R.attr.outerCircleWidth, com.coloros.translate.R.attr.outerUnCheckedCircleColor, com.coloros.translate.R.attr.themedCheckedDrawable, com.coloros.translate.R.attr.themedLoadingCheckedBackground, com.coloros.translate.R.attr.themedLoadingDrawable, com.coloros.translate.R.attr.themedLoadingUncheckedBackground, com.coloros.translate.R.attr.themedUncheckedDrawable};
    public static int[] COUITextAppearance = {R.attr.lineSpacingMultiplier, com.coloros.translate.R.attr.lineSpacingMultiplier};
    public static int[] COUITextView = {R.attr.textAppearance, R.attr.lineSpacingMultiplier};
    public static int[] COUITheme = {com.coloros.translate.R.attr.couiEmptyHint, com.coloros.translate.R.attr.couiIsSplitHideWithActionBar, com.coloros.translate.R.attr.isCOUIDarkTheme, com.coloros.translate.R.attr.isCOUITheme, com.coloros.translate.R.attr.startingWindowTitle, com.coloros.translate.R.attr.windowPreviewType, com.coloros.translate.R.attr.windowSnapshotPreviewToken};

    private R$styleable() {
    }
}
